// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/media/v2/file.proto (package sited_io.media.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum sited_io.media.v2.ContentType
 */
export enum ContentType {
  /**
   * @generated from enum value: CONTENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONTENT_TYPE_IMAGE = 1;
   */
  IMAGE = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(ContentType)
proto3.util.setEnumType(ContentType, "sited_io.media.v2.ContentType", [
  { no: 0, name: "CONTENT_TYPE_UNSPECIFIED" },
  { no: 1, name: "CONTENT_TYPE_IMAGE" },
]);

/**
 * @generated from message sited_io.media.v2.File
 */
export class File extends Message<File> {
  /**
   * @generated from field: string file_id = 1;
   */
  fileId = "";

  /**
   * @generated from field: string owner = 2;
   */
  owner = "";

  /**
   * @generated from field: int64 created_at = 3;
   */
  createdAt = protoInt64.zero;

  /**
   * @generated from field: int64 updated_at = 4;
   */
  updatedAt = protoInt64.zero;

  /**
   * @generated from field: sited_io.media.v2.ContentType content_type = 5;
   */
  contentType = ContentType.UNSPECIFIED;

  /**
   * @generated from field: string file_name = 6;
   */
  fileName = "";

  /**
   * @generated from field: optional string file_url = 7;
   */
  fileUrl?: string;

  constructor(data?: PartialMessage<File>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.media.v2.File";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "file_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "owner", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "created_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 4, name: "updated_at", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 5, name: "content_type", kind: "enum", T: proto3.getEnumType(ContentType) },
    { no: 6, name: "file_name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "file_url", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): File {
    return new File().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): File {
    return new File().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): File {
    return new File().fromJsonString(jsonString, options);
  }

  static equals(a: File | PlainMessage<File> | undefined, b: File | PlainMessage<File> | undefined): boolean {
    return proto3.util.equals(File, a, b);
  }
}

