// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file sited_io/media/v2/media_service.proto (package sited_io.media.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { DeleteFileRequest, DeleteFileResponse, UploadFileRequest, UploadFileResponse } from "./media_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sited_io.media.v2.MediaService
 */
export const MediaService = {
  typeName: "sited_io.media.v2.MediaService",
  methods: {
    /**
     * @generated from rpc sited_io.media.v2.MediaService.UploadFile
     */
    uploadFile: {
      name: "UploadFile",
      I: UploadFileRequest,
      O: UploadFileResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.media.v2.MediaService.DeleteFile
     */
    deleteFile: {
      name: "DeleteFile",
      I: DeleteFileRequest,
      O: DeleteFileResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

