// @generated by protoc-gen-connect-es v1.5.0 with parameter "target=ts"
// @generated from file sited_io/commerce/v2/commerce_service.proto (package sited_io.commerce.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddImageToOfferRequest, AddImageToOfferResponse, AddOfferToShopRequest, AddOfferToShopResponse, AddShippingRateToOfferRequest, AddShippingRateToOfferResponse, CreateOfferRequest, CreateOfferResponse, CreateShopRequest, CreateShopResponse, DeleteOfferRequest, DeleteOfferResponse, DeleteShopRequest, DeleteShopResponse, GetOfferRequest, GetOfferResponse, GetShopRequest, GetShopResponse, ListOffersRequest, ListOffersResponse, PutPriceToOfferRequest, PutPriceToOfferResponse, RemoveImageFromOfferRequest, RemoveImageFromOfferResponse, RemoveOfferFromShopRequest, RemoveOfferFromShopResponse, RemovePriceFromOfferRequest, RemovePriceFromOfferResponse, RemoveShippingRateFromOfferRequest, RemoveShippingRateFromOfferResponse, UpdateOfferRequest, UpdateOfferResponse } from "./commerce_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service sited_io.commerce.v2.CommerceService
 */
export const CommerceService = {
  typeName: "sited_io.commerce.v2.CommerceService",
  methods: {
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.CreateOffer
     */
    createOffer: {
      name: "CreateOffer",
      I: CreateOfferRequest,
      O: CreateOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.GetOffer
     */
    getOffer: {
      name: "GetOffer",
      I: GetOfferRequest,
      O: GetOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.ListOffers
     */
    listOffers: {
      name: "ListOffers",
      I: ListOffersRequest,
      O: ListOffersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.UpdateOffer
     */
    updateOffer: {
      name: "UpdateOffer",
      I: UpdateOfferRequest,
      O: UpdateOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.DeleteOffer
     */
    deleteOffer: {
      name: "DeleteOffer",
      I: DeleteOfferRequest,
      O: DeleteOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.PutPriceToOffer
     */
    putPriceToOffer: {
      name: "PutPriceToOffer",
      I: PutPriceToOfferRequest,
      O: PutPriceToOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.RemovePriceFromOffer
     */
    removePriceFromOffer: {
      name: "RemovePriceFromOffer",
      I: RemovePriceFromOfferRequest,
      O: RemovePriceFromOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.AddShippingRateToOffer
     */
    addShippingRateToOffer: {
      name: "AddShippingRateToOffer",
      I: AddShippingRateToOfferRequest,
      O: AddShippingRateToOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.RemoveShippingRateFromOffer
     */
    removeShippingRateFromOffer: {
      name: "RemoveShippingRateFromOffer",
      I: RemoveShippingRateFromOfferRequest,
      O: RemoveShippingRateFromOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.AddImageToOffer
     */
    addImageToOffer: {
      name: "AddImageToOffer",
      I: AddImageToOfferRequest,
      O: AddImageToOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.RemoveImageFromOffer
     */
    removeImageFromOffer: {
      name: "RemoveImageFromOffer",
      I: RemoveImageFromOfferRequest,
      O: RemoveImageFromOfferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.CreateShop
     */
    createShop: {
      name: "CreateShop",
      I: CreateShopRequest,
      O: CreateShopResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.GetShop
     */
    getShop: {
      name: "GetShop",
      I: GetShopRequest,
      O: GetShopResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.DeleteShop
     */
    deleteShop: {
      name: "DeleteShop",
      I: DeleteShopRequest,
      O: DeleteShopResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.AddOfferToShop
     */
    addOfferToShop: {
      name: "AddOfferToShop",
      I: AddOfferToShopRequest,
      O: AddOfferToShopResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc sited_io.commerce.v2.CommerceService.RemoveOfferFromShop
     */
    removeOfferFromShop: {
      name: "RemoveOfferFromShop",
      I: RemoveOfferFromShopRequest,
      O: RemoveOfferFromShopResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

