// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file sited_io/commerce/v2/query.proto (package sited_io.commerce.v2, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import { Direction } from "../../query/v1/query_pb.js";

/**
 * @generated from enum sited_io.commerce.v2.OffersOrderByField
 */
export enum OffersOrderByField {
  /**
   * @generated from enum value: OFFERS_ORDER_BY_FIELD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: OFFERS_ORDER_BY_FIELD_CREATED_AT = 1;
   */
  CREATED_AT = 1,

  /**
   * @generated from enum value: OFFERS_ORDER_BY_FIELD_UPDATED_AT = 2;
   */
  UPDATED_AT = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(OffersOrderByField)
proto3.util.setEnumType(OffersOrderByField, "sited_io.commerce.v2.OffersOrderByField", [
  { no: 0, name: "OFFERS_ORDER_BY_FIELD_UNSPECIFIED" },
  { no: 1, name: "OFFERS_ORDER_BY_FIELD_CREATED_AT" },
  { no: 2, name: "OFFERS_ORDER_BY_FIELD_UPDATED_AT" },
]);

/**
 * @generated from enum sited_io.commerce.v2.OffersFilterField
 */
export enum OffersFilterField {
  /**
   * @generated from enum value: OFFERS_FILTER_FIELD_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: OFFERS_FILTER_FIELD_NAME = 1;
   */
  NAME = 1,

  /**
   * @generated from enum value: OFFERS_FILTER_FIELD_DESCRIPTION = 2;
   */
  DESCRIPTION = 2,

  /**
   * @generated from enum value: OFFERS_FILTER_FIELD_NAME_AND_DESCRIPTION = 3;
   */
  NAME_AND_DESCRIPTION = 3,

  /**
   * @generated from enum value: OFFERS_FILTER_FIELD_TYPE = 4;
   */
  TYPE = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(OffersFilterField)
proto3.util.setEnumType(OffersFilterField, "sited_io.commerce.v2.OffersFilterField", [
  { no: 0, name: "OFFERS_FILTER_FIELD_UNSPECIFIED" },
  { no: 1, name: "OFFERS_FILTER_FIELD_NAME" },
  { no: 2, name: "OFFERS_FILTER_FIELD_DESCRIPTION" },
  { no: 3, name: "OFFERS_FILTER_FIELD_NAME_AND_DESCRIPTION" },
  { no: 4, name: "OFFERS_FILTER_FIELD_TYPE" },
]);

/**
 * @generated from message sited_io.commerce.v2.OffersOrderBy
 */
export class OffersOrderBy extends Message<OffersOrderBy> {
  /**
   * @generated from field: sited_io.commerce.v2.OffersOrderByField field = 1;
   */
  field = OffersOrderByField.UNSPECIFIED;

  /**
   * @generated from field: sited_io.query.v1.Direction direction = 2;
   */
  direction = Direction.UNSPECIFIED;

  constructor(data?: PartialMessage<OffersOrderBy>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v2.OffersOrderBy";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "field", kind: "enum", T: proto3.getEnumType(OffersOrderByField) },
    { no: 2, name: "direction", kind: "enum", T: proto3.getEnumType(Direction) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OffersOrderBy {
    return new OffersOrderBy().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OffersOrderBy {
    return new OffersOrderBy().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OffersOrderBy {
    return new OffersOrderBy().fromJsonString(jsonString, options);
  }

  static equals(a: OffersOrderBy | PlainMessage<OffersOrderBy> | undefined, b: OffersOrderBy | PlainMessage<OffersOrderBy> | undefined): boolean {
    return proto3.util.equals(OffersOrderBy, a, b);
  }
}

/**
 * @generated from message sited_io.commerce.v2.OffersFilter
 */
export class OffersFilter extends Message<OffersFilter> {
  /**
   * @generated from field: sited_io.commerce.v2.OffersFilterField field = 1;
   */
  field = OffersFilterField.UNSPECIFIED;

  /**
   * @generated from field: string query = 2;
   */
  query = "";

  constructor(data?: PartialMessage<OffersFilter>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "sited_io.commerce.v2.OffersFilter";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "field", kind: "enum", T: proto3.getEnumType(OffersFilterField) },
    { no: 2, name: "query", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OffersFilter {
    return new OffersFilter().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OffersFilter {
    return new OffersFilter().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OffersFilter {
    return new OffersFilter().fromJsonString(jsonString, options);
  }

  static equals(a: OffersFilter | PlainMessage<OffersFilter> | undefined, b: OffersFilter | PlainMessage<OffersFilter> | undefined): boolean {
    return proto3.util.equals(OffersFilter, a, b);
  }
}

